kind: Deployment
apiVersion: apps/v1
metadata:
  name: api1
  namespace: example
  labels:
    app.kubernetes.io/name: api1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api1
    spec:
      containers:
        - name: api1
          image: registry.kthcloud.com/examples/api1-example
---
kind: Service
apiVersion: v1
metadata:
  name: api1
  namespace: example
  labels:
    app.kubernetes.io/name: api1
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: api1