name: go-api
"on":
  push:
    branches:
      - main
    paths:
      - apis/go/**
      - .github/workflows/go-api.yml
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME_GO_API }}
          password: ${{ secrets.DOCKER_PASSWORD_GO_API }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./apis/go/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_TAG_GO_API }}
          context: "{{defaultContext}}:/apis/go"
