name: websockets-backend
"on":
  push:
    branches:
      - main
    paths:
      - websockets/**
      - .github/workflows/websockets-backend.yml
      workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME_WEBSOCKETS_BACKEND }}
          password: ${{ secrets.DOCKER_PASSWORD_WEBSOCKETS_BACKEND }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./websockets/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_TAG_WEBSOCKETS_BACKEND }}
